// This file has been autogenerated from a class added in the UI designer.

using System;
using core.Models;
using CoreGraphics;
using Foundation;
using UIKit;

namespace ui_kit_mvvm_ios
{
	public partial class UsersTableViewCell : UITableViewCell
	{
        public static readonly NSString Key = new NSString("UsersTableViewCell");
        public static readonly UINib Nib = UINib.FromName("UsersTableViewCell", NSBundle.MainBundle);

        public UserResponse User;

		public UsersTableViewCell (IntPtr handle) : base (handle)
		{
		}

		public void UpdateViews()
		{
			if (User == null) return;
			Layer.CornerRadius = 8;
			ClipsToBounds = true;

            userNameLabel.Text = User.Username;
			emailLabel.Text = User.Email;
			phoneLabel.Text = User.Phone;
		}
	}
}
